---

- hosts: localhost

  tasks:

  # - name: dependancy
  #   dnf:
  #     name:
  #       - python3-dnf
  #       - ansible-collection-microsoft-sql
  #       - rhel-system-roles
  #     state: latest
    shell: "hi"
    # shell: "yum install -y ansible-collection-microsoft-sql rhel-system-roles"


  # vars:
  #   mssql_accept_microsoft_odbc_driver_17_for_sql_server_eula: true
  #   mssql_accept_microsoft_cli_utilities_for_sql_server_eula: true
  #   mssql_accept_microsoft_sql_server_standard_eula: true
  #   mssql_password: "YourP@ssw0rd"
  #   mssql_edition: Evaluation
  #   mssql_enable_sql_agent: true
  #   mssql_install_fts: true
  #   mssql_install_powershell: true
  #   mssql_tune_for_fua_storage: true
  # roles:
  #   - microsoft.sql.server
